ERROR_MAP = {
    '999': 'Request URL is not valid.', # custom
    '151': "It's V2 API. V1 Access token is not acceptable",
    '150': "It's V1 API. V2 Access token is not acceptable",
    '1209': 'User not found',
    '1208': 'User not found',
    '210': 'Limitation error',
    '1205': 'API Key error',
    '312': 'Name is not correct',
    '311': 'Need mobile auth',
    '310': 'Mobile auth error',
    '330': 'Phone number error',
    '1203': 'Already registered',
    '1202': 'App not found',
    '132': 'V2 API body is corrupted',
    '131': 'V2 API Nonce is must be bigger then last nonce',
    '130': 'V2 API Nonce value must be a positive integer',
    '111': 'Order id is not exist',
    '113': 'Quantity is too low(ETH, ETC > 0.01)',
    '112': 'Cancel failed',
    '40': 'Invalid API permission',
    '405': 'Server error',
    '404': 'Page not found error',
    '4': 'Blocked user access',
    '1204': 'Invalid access',
    '220': 'Limitation error',
    '1207': 'User not found',
    '500': 'Email error',
    '501': 'Email error',
    '200': 'Wallet Error',
    '777': 'Mobile auth error',
    '202': 'Limitation error',
    '221': 'Limitation error',
    '141': 'Too many limit orders',
    '779': 'Address error',
    '778': 'Phone number error',
    '444': 'Locking error',
    '120': 'V2 API payload is missing',
    '121': 'V2 API signature is missing',
    '122': 'V2 API nonce is missing',
    '123': 'V2 API signature is not correct',
    '102': 'ID is not exist',
    '103': 'Lack of Balance',
    '100': 'Session expired',
    '101': 'Invalid format',
    '106': 'Locking error',
    '107': 'Parameter error',
    '104': 'Order id is not exist',
    '105': 'Price is not correct',
    '11': 'Access token is missing',
    '12': 'Invalid access token',
    '1206': 'User not found',
    '51': 'Invalid API',
    '50': 'Authenticate error',
    '53': 'Two Factor Auth Fail',
    '52': 'Deprecated API'
}
